server:
  port: 8081

spring:
  application:
    name: rocketmq-producer-a1

rocketmq:
  name-server: localhost:9876
  # org.apache.rocketmq.spring.autoconfigure.RocketMQProperties.Producer
  producer:
    # 生产者组
    group: my-producer-group1
    # 超时时间
    sendMessageTimeout: 5000
    # 同步发送消息失败重试次数
    retry-times-when-send-failed: 4
    # 异步发送消息失败重试次数
    retry-times-when-send-async-failed: 4
    # TLS 通信加密
    tls-enable: false
    # 可以将accessKey和secretKey理解成用户名和密码
#    access-key: testACL
    access-key: adminACL
    secret-key: 12345678

# properties used in the application
demo:
  rocketmq:
    topic: string-topic
    user-topic: user-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    denyTopic: deny-topic
    onlySubTopic: only-sub-topic
    defaultTestTopic: default-test-topic

    bytesRequestTopic: bytesRequestTopic:tagA
    stringRequestTopic: stringRequestTopic:tagA
    objectRequestTopic: objectRequestTopic:tagA
    genericRequestTopic: genericRequestTopic:tagA

    # self ext producer tls config
    ext:
      useTLS: false
      nameServer: 127.0.0.1:9876
    producer-group: demo-producer-group

order:
  rocketmq:
    name-server: 127.0.0.1:9876
    tls-enable: false
    topic: trans-order-topic
    tag-order: tag-order
    order-producer-group: trans-order-producer-group
