server:
  port: 8082

spring:
  application:
    name: rocketmq-consumer-a1

rocketmq:
  name-server: localhost:9876
  consumer:
    group: my-group1
    topic: test
    # default LitePullConsumer TLS
    tlsEnable: false

demo:
  rocketmq:
    topic: string-topic
    user-topic: user-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic

    bytesRequestTopic: bytesRequestTopic
    genericRequestTopic: genericRequestTopic
    objectRequestTopic: objectRequestTopic
    stringRequestTopic: stringRequestTopic

    bytesRequestConsumer: bytesRequestConsumer
    genericRequestConsumer: genericRequestConsumer
    objectRequestConsumer: objectRequestConsumer
    stringRequestConsumer: stringRequestConsumer

    consumer:
      group: demo-consumer-group
    order-consumer:
      group: order-paid-consumer-group
    trans-consumer:
      group: string-trans-consumer-group
    user-consumer:
      group: user-consumer-group
    string-newns-consumer:
      group: string-newns-consumer-group
    message-ext-consumer:
      group: message-ext-consumer-group

    tag: tagA
    # my Consumer TLS Listener
    tlsEnable: false
    # another nameserver different global
    myNameServer: 127.0.0.1:9876

  # ext rocketmq consumer template TLS
  ext:
    consumer:
      tlsEnable: false
